### ISSUE TITLE
paddle与onnx兼容性问题

### ISSUE THREAD

**Issue by weirman** [jiangjiajun/PaddleUtils#4]
大佬好，我使用 `paddle2onnx --input_shape_dict` 出现

>  [WARNING]	[Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle

所以打算使用`paddle_infer_shape.py`来解决这个问题，但是发现以下异常：
```
  File "paddle_infer_shape.py", line 54, in <module>
    import paddle.fluid as fluid
ModuleNotFoundError: No module named 'paddle.fluid'
```

查看后[官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.5/api/paddle/fluid/Overview_cn.html)发现在paddle2.5的时候已经遗弃了`paddle.fluid`。

这个问题大佬还会再跟进修复吗？以及`--input_shape_dict`动态输入是否有其他解决方案呢？

**Comment by weirman** [comment]
已解决，发现[官方](https://github.com/PaddlePaddle/Paddle2ONNX?tab=readme-ov-file#paddle2onnx)有解决方案，可能是 `paddle2onnx` 没有及时更改输出信息？

```python
python -m paddle2onnx.optimize --input_model model.onnx \
                               --output_model new_model.onnx \
                               --input_shape_dict "{'x':[1,3,224,224]}"
```

**Comment by happygb21** [comment]
paddle.fluid 请问如何解决
